# Generated by Django 3.2.4 on 2021-06-11 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_matricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='Aluno',
            new_name='aluno',
        ),
    ]
